package main;

public class TryCatch {

	public static void main(String[] args) {
		call();
	}

	private static void call() {
		// TODO Auto-generated method stub
		for(int i=0; i<5; i++)
		{
			try {
				i = i/i;
			}
			catch(ArithmeticException e)
			{
				System.out.println("Arithmetic exception called");
				i=0;
			}
			
			System.out.println("after try/catch - "+ i);
		}
	}
}
